[package]
name = "yilmazrs"
version = "0.1.0"
authors = ["Liam Borella <ulfrthewolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.8"
nalgebra = "0.18.1"
